# Generated by Django 5.2.17 on 2026-09-16 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=16)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='curriculum.world')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learners.learnerprofile')),
            ],
            options={
                'ordering': ['enrolled_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'world'), name='learners_enrollment_unique_learner_world', violation_error_message='This learner is already enrolled in this World.'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'paused', 'completed'])), name='learners_enrollment_status_valid')],
            },
        ),
    ]
