# Generated by Django 5.2.17 on 2026-09-17 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_world_domain'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('brief', models.TextField()),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('estimated_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('xp_reward', models.PositiveIntegerField(default=150, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='curriculum.world')),
            ],
            options={
                'ordering': ['world__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectConceptRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_mastery', models.PositiveSmallIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requirements', to='curriculum.concept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project')),
            ],
            options={
                'ordering': ['concept__skill__order', 'concept__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('objective', models.CharField(max_length=300)),
                ('instructions', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('starter_code', models.TextField(blank=True)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_drafts', to='learners.enrollment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='projects.project')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectstage')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('submitted_source', models.TextField()),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('invalid', 'Invalid'), ('unsupported', 'Unsupported'), ('unavailable', 'Unavailable')], max_length=32)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('evaluator', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=300)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(86400)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_submissions', to='learners.enrollment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='projects.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='projects.projectstage')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_completions', to='learners.enrollment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='projects.project')),
                ('final_submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.projectsubmission')),
            ],
            options={
                'ordering': ['completed_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='projects_project_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('world', 'order'), name='projects_project_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='projects_project_order_pos'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('xp_reward__gt', 0)), name='projects_project_xp_positive'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_minutes__gt', 0)), name='projects_project_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__in', ['beginner', 'intermediate', 'advanced'])), name='projects_project_difficulty_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectconceptrequirement',
            constraint=models.UniqueConstraint(fields=('project', 'concept'), name='projects_requirement_unique_concept'),
        ),
        migrations.AddConstraint(
            model_name='projectconceptrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_mastery__gte', 0), ('minimum_mastery__lte', 100)), name='projects_requirement_mastery_range'),
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='projects_stage_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='projects_stage_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='projects_stage_order_pos'),
        ),
        migrations.AddConstraint(
            model_name='projectdraft',
            constraint=models.UniqueConstraint(fields=('enrollment', 'project'), name='projects_draft_unique_project'),
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['enrollment', 'project', 'stage'], name='projects_pr_enrollm_dc9f16_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsubmission',
            index=models.Index(fields=['enrollment', 'submitted_at'], name='projects_pr_enrollm_5ce205_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.UniqueConstraint(fields=('enrollment', 'stage', 'attempt_number'), name='projects_submission_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['correct', 'incorrect', 'invalid', 'unsupported', 'unavailable'])), name='projects_submission_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 1)), _connector='OR'), name='projects_submission_score_range'),
        ),
        migrations.AddConstraint(
            model_name='projectcompletion',
            constraint=models.UniqueConstraint(fields=('enrollment', 'project'), name='projects_completion_unique'),
        ),
    ]
