# Generated by Django 5.2.17 on 2026-09-16 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('submitted_answer', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('invalid', 'Invalid'), ('review_required', 'Review required'), ('unsupported', 'Unsupported'), ('unavailable', 'Unavailable')], max_length=32)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('evaluator', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=300)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('hint_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('used_explanation', models.BooleanField(default=False)),
                ('used_solution', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(86400)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='learners.enrollment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exercises.exercise')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='attempts.exerciseattempt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['enrollment', 'exercise', '-submitted_at'], name='attempts_ex_enrollm_f7c473_idx'),
        ),
        migrations.AddConstraint(
            model_name='exerciseattempt',
            constraint=models.UniqueConstraint(fields=('enrollment', 'exercise', 'attempt_number'), name='attempts_attempt_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='exerciseattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='attempts_attempt_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='exerciseattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['correct', 'incorrect', 'invalid', 'review_required', 'unsupported', 'unavailable'])), name='attempts_attempt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='exerciseattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 1)), _connector='OR'), name='attempts_attempt_score_range'),
        ),
        migrations.AddConstraint(
            model_name='exerciseattempt',
            constraint=models.CheckConstraint(condition=models.Q(('hint_level__lte', 10)), name='attempts_attempt_hint_level_range'),
        ),
        migrations.AddConstraint(
            model_name='exerciseattempt',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__lte', 86400), _connector='OR'), name='attempts_attempt_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='attemptmistake',
            constraint=models.UniqueConstraint(fields=('attempt', 'code'), name='attempts_mistake_unique_code'),
        ),
    ]
