# Generated by Django 5.2.17 on 2026-09-17 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('exercises', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorExerciseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('used_explanation', models.BooleanField(default=False)),
                ('used_solution', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_exercise_states', to='learners.enrollment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_exercise_states', to='exercises.exercise')),
                ('last_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attempts.exerciseattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'exercise'), name='ai_tutor_state_unique_exercise'), models.CheckConstraint(condition=models.Q(('hint_level__lte', 2)), name='ai_tutor_state_hint_level')],
            },
        ),
        migrations.CreateModel(
            name='TutorTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_intent', models.CharField(choices=[('ask', 'Ask'), ('hint', 'Hint'), ('explain', 'Explain'), ('solution', 'Solution'), ('next_step', 'Next step')], max_length=16)),
                ('response_kind', models.CharField(blank=True, choices=[('guidance', 'Guidance'), ('hint', 'Hint'), ('strong_hint', 'Strong hint'), ('explanation', 'Explanation'), ('solution', 'Solution'), ('feedback', 'Feedback'), ('next_step', 'Next step')], max_length=16)),
                ('user_message', models.TextField(blank=True)),
                ('assistant_message', models.TextField(blank=True)),
                ('should_retry', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.PositiveSmallIntegerField()),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_response_id', models.CharField(blank=True, max_length=128)),
                ('error_code', models.SlugField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_turns', to='attempts.exerciseattempt')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_turns', to='learners.enrollment')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_turns', to='exercises.exercise')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['enrollment', 'created_at'], name='ai_tutor_turn_recent'), models.Index(fields=['enrollment', 'status', 'created_at'], name='ai_tutor_turn_history')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_intent__in', ['ask', 'hint', 'explain', 'solution', 'next_step'])), name='ai_tutor_turn_intent'), models.CheckConstraint(condition=models.Q(('response_kind', ''), ('response_kind__in', ['guidance', 'hint', 'strong_hint', 'explanation', 'solution', 'feedback', 'next_step']), _connector='OR'), name='ai_tutor_turn_kind'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'complete', 'failed'])), name='ai_tutor_turn_status')],
            },
        ),
    ]
