# Generated by Django 5.2.17 on 2026-09-17 10:48

from django.db import migrations, models
from django.db.models import F


def backfill_completed_at(apps, schema_editor):
    TutorTurn = apps.get_model("ai_tutor", "TutorTurn")
    # Historical fallback: finished turns completed when they were created.
    TutorTurn.objects.filter(status__in=["complete", "failed"]).update(
        completed_at=F("created_at")
    )
    # Turns left pending by earlier versions can never finish; release them before the
    # one-pending-per-exercise constraint is created.
    TutorTurn.objects.filter(status="pending").update(
        status="failed", error_code="stale_pending_turn", completed_at=F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0001_initial'),
        ('attempts', '0001_initial'),
        ('exercises', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorturn',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tutorturn',
            constraint=models.UniqueConstraint(condition=models.Q(('exercise__isnull', False), ('status', 'pending')), fields=('enrollment', 'exercise'), name='ai_tutor_turn_one_pending_exercise'),
        ),
    ]
