# Generated by Django 5.2.17 on 2026-09-17 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0002_pending_reservation'),
        ('attempts', '0001_initial'),
        ('exercises', '0001_initial'),
        ('learners', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorturn',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_turns', to='projects.project'),
        ),
        migrations.AddField(
            model_name='tutorturn',
            name='project_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_turns', to='projects.projectstage'),
        ),
        migrations.AddIndex(
            model_name='tutorturn',
            index=models.Index(fields=['enrollment', 'project', 'status', 'created_at'], name='ai_tutor_turn_project'),
        ),
        migrations.AddConstraint(
            model_name='tutorturn',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False), ('status', 'pending')), fields=('enrollment', 'project'), name='ai_tutor_turn_one_pending_project'),
        ),
        migrations.AddConstraint(
            model_name='tutorturn',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', True), models.Q(('attempt__isnull', True), ('exercise__isnull', True)), _connector='OR'), name='ai_tutor_turn_project_or_exercise'),
        ),
        migrations.AddConstraint(
            model_name='tutorturn',
            constraint=models.CheckConstraint(condition=models.Q(('project_stage__isnull', True), ('project__isnull', False), _connector='OR'), name='ai_tutor_turn_stage_needs_project'),
        ),
    ]
