# Generated by Django 5.2.17 on 2026-09-16 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['world_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('learning_objective', models.TextField(help_text='What the learner should be able to do after mastering this concept.')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='curriculum.skill')),
            ],
            options={
                'ordering': ['skill_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_links', to='curriculum.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='curriculum.skill')),
            ],
            options={
                'ordering': ['skill_id', 'prerequisite_id'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='curriculum_world_unique_slug'), models.UniqueConstraint(fields=('order',), name='curriculum_world_unique_order'), models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='curriculum_world_order_positive', violation_error_message='Order must be greater than zero.')],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='curriculum.world'),
        ),
        migrations.CreateModel(
            name='ConceptPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='curriculum.concept')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_links', to='curriculum.concept')),
            ],
            options={
                'ordering': ['concept_id', 'prerequisite_id'],
                'constraints': [models.UniqueConstraint(fields=('concept', 'prerequisite'), name='curriculum_conceptprerequisite_unique_edge'), models.CheckConstraint(condition=models.Q(('concept', models.F('prerequisite')), _negated=True), name='curriculum_conceptprerequisite_not_self', violation_error_message='A concept cannot require itself.')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('objective', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('kind', models.CharField(choices=[('learn', 'Learn'), ('practice', 'Practice'), ('review', 'Review'), ('challenge', 'Challenge')], default='learn', max_length=16)),
                ('is_published', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.concept')),
            ],
            options={
                'ordering': ['concept_id', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('concept', 'slug'), name='curriculum_lesson_unique_concept_slug'), models.UniqueConstraint(fields=('concept', 'order'), name='curriculum_lesson_unique_concept_order'), models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='curriculum_lesson_order_positive', violation_error_message='Order must be greater than zero.'), models.CheckConstraint(condition=models.Q(('estimated_minutes__gt', 0)), name='curriculum_lesson_estimated_minutes_positive', violation_error_message='Estimated minutes must be greater than zero.')],
            },
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('skill', 'slug'), name='curriculum_concept_unique_skill_slug'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('skill', 'order'), name='curriculum_concept_unique_skill_order'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='curriculum_concept_order_positive', violation_error_message='Order must be greater than zero.'),
        ),
        migrations.AddConstraint(
            model_name='skillprerequisite',
            constraint=models.UniqueConstraint(fields=('skill', 'prerequisite'), name='curriculum_skillprerequisite_unique_edge'),
        ),
        migrations.AddConstraint(
            model_name='skillprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('skill', models.F('prerequisite')), _negated=True), name='curriculum_skillprerequisite_not_self', violation_error_message='A skill cannot require itself.'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='curriculum_skill_unique_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('world', 'order'), name='curriculum_skill_unique_world_order'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='curriculum_skill_order_positive', violation_error_message='Order must be greater than zero.'),
        ),
    ]
