# Generated by Django 5.2.17 on 2026-09-17 10:50

from django.db import migrations, models

# The seeded Python Foundations World. Matching its slug is acceptable here, once, to
# backfill existing databases; runtime code only ever reads World.domain.
PYTHON_WORLD_SLUG = "python-foundations"


def set_python_domain(apps, schema_editor):
    World = apps.get_model("curriculum", "World")
    World.objects.filter(slug=PYTHON_WORLD_SLUG).update(domain="python")


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='domain',
            field=models.SlugField(default='general'),
        ),
        migrations.RunPython(set_python_domain, migrations.RunPython.noop),
    ]
