# Generated by Django 5.2.17 on 2026-09-16 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('prompt', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('response_type', models.CharField(choices=[('code', 'Code'), ('multiple_choice', 'Multiple choice'), ('fill_gap', 'Fill the gap'), ('text', 'Text'), ('translation', 'Translation'), ('numeric', 'Numeric'), ('math_expression', 'Math expression'), ('speaking', 'Speaking'), ('listening', 'Listening')], max_length=32)),
                ('learning_mode', models.CharField(choices=[('recognise', 'Recognise'), ('complete', 'Complete'), ('fix', 'Fix'), ('create', 'Create')], max_length=16)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Learner-facing data needed to present the exercise. Never put answers here.')),
                ('evaluation_spec', models.JSONField(blank=True, default=dict, help_text='Private configuration for evaluating answers. Never shown to learners.')),
                ('target_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['lesson__concept__skill__world__order', 'lesson__concept__skill__order', 'lesson__concept__order', 'lesson__order', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'slug'), name='exercises_exercise_unique_lesson_slug'), models.UniqueConstraint(fields=('lesson', 'order'), name='exercises_exercise_unique_lesson_order'), models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='exercises_exercise_order_positive', violation_error_message='Order must be greater than zero.'), models.CheckConstraint(condition=models.Q(('target_seconds__isnull', True), ('target_seconds__gt', 0), _connector='OR'), name='exercises_exercise_target_seconds_positive', violation_error_message='Target seconds must be greater than zero.'), models.CheckConstraint(condition=models.Q(('response_type__in', ['code', 'multiple_choice', 'fill_gap', 'text', 'translation', 'numeric', 'math_expression', 'speaking', 'listening'])), name='exercises_exercise_response_type_valid'), models.CheckConstraint(condition=models.Q(('learning_mode__in', ['recognise', 'complete', 'fix', 'create'])), name='exercises_exercise_learning_mode_valid')],
            },
        ),
    ]
