# Generated by Django 5.2.17 on 2026-09-17 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('curriculum', '0002_world_domain'),
        ('exercises', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('icon_key', models.SlugField(blank=True, max_length=32)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic')], default='common', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rarity__in', ['common', 'uncommon', 'rare', 'epic'])), name='gamification_achievement_rarity_valid')],
            },
        ),
        migrations.CreateModel(
            name='BossChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_xp', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='exercises.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BossCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attempts.exerciseattempt')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='gamification.bosschallenge')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_completions', to='learners.enrollment')),
            ],
            options={
                'ordering': ['completed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to='learners.learnerprofile')),
            ],
            options={
                'ordering': ['learner_id'],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('exercise_completed', 'Exercise completed'), ('first_try', 'First-try bonus'), ('independence', 'Independence bonus'), ('skill_mastered', 'Skill mastered'), ('boss_completed', 'Boss completed')], max_length=32)),
                ('xp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('source_key', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='attempts.exerciseattempt')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='learners.enrollment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to='learners.learnerprofile')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xp_events', to='curriculum.world')),
            ],
            options={
                'verbose_name': 'XP event',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AchievementAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='gamification.achievement')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attempts.exerciseattempt')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learners.enrollment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_awards', to='learners.learnerprofile')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.world')),
            ],
            options={
                'ordering': ['awarded_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'achievement'), name='gamification_award_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='bosschallenge',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_xp__gt', 0)), name='gamification_boss_bonus_positive'),
        ),
        migrations.AddConstraint(
            model_name='bosscompletion',
            constraint=models.UniqueConstraint(fields=('enrollment', 'boss'), name='gamification_boss_completion_unique'),
        ),
        migrations.AddConstraint(
            model_name='gamificationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('longest_streak__gte', models.F('current_streak'))), name='gamification_profile_longest_covers_current'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['learner', '-created_at'], name='gamificatio_learner_77d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['world', 'event_type'], name='gamificatio_world_i_fb99f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='xpevent',
            constraint=models.UniqueConstraint(fields=('learner', 'source_key'), name='gamification_xp_event_unique_source'),
        ),
        migrations.AddConstraint(
            model_name='xpevent',
            constraint=models.CheckConstraint(condition=models.Q(('xp__gt', 0)), name='gamification_xp_event_positive'),
        ),
        migrations.AddConstraint(
            model_name='xpevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['exercise_completed', 'first_try', 'independence', 'skill_mastered', 'boss_completed'])), name='gamification_xp_event_type_valid'),
        ),
    ]
