# Generated by Django 5.2.17 on 2026-09-17 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('curriculum', '0002_world_domain'),
        ('gamification', '0002_seed_achievements'),
        ('learners', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='xpevent',
            name='gamification_xp_event_type_valid',
        ),
        migrations.AddField(
            model_name='achievementaward',
            name='project_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectsubmission'),
        ),
        migrations.AddField(
            model_name='xpevent',
            name='project_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='projects.projectsubmission'),
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='event_type',
            field=models.CharField(choices=[('exercise_completed', 'Exercise completed'), ('first_try', 'First-try bonus'), ('independence', 'Independence bonus'), ('skill_mastered', 'Skill mastered'), ('boss_completed', 'Boss completed'), ('project_completed', 'Project completed')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='xpevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['exercise_completed', 'first_try', 'independence', 'skill_mastered', 'boss_completed', 'project_completed'])), name='gamification_xp_event_type_valid'),
        ),
    ]
