# Generated by Django 5.2.17 on 2026-09-17 08:58

import apps.misconceptions.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisconceptionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, validators=[apps.misconceptions.models._validate_code])),
                ('kind', models.CharField(choices=[('positive', 'Supports'), ('counter', 'Counters')], max_length=16)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('source', models.CharField(max_length=64, validators=[apps.misconceptions.models._validate_code])),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconception_evidence', to='attempts.exerciseattempt')),
            ],
            options={
                'verbose_name_plural': 'misconception evidence',
                'ordering': ['attempt_id', 'code', 'kind', 'source'],
                'indexes': [models.Index(fields=['code', 'kind'], name='misconc_evidence_code_kind')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'code', 'kind', 'source'), name='misconceptions_evidence_unique_signal'), models.CheckConstraint(condition=models.Q(('kind__in', ['positive', 'counter'])), name='misconceptions_evidence_kind'), models.CheckConstraint(condition=models.Q(('strength__gte', 0), ('strength__lte', 1)), name='misconceptions_evidence_strength_range')],
            },
        ),
        migrations.CreateModel(
            name='MisconceptionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, validators=[apps.misconceptions.models._validate_code])),
                ('status', models.CharField(choices=[('watch', 'Watch'), ('active', 'Active'), ('resolved', 'Resolved')], max_length=16)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('positive_evidence_count', models.PositiveIntegerField(default=0)),
                ('counter_evidence_count', models.PositiveIntegerField(default=0)),
                ('strong_evidence_count', models.PositiveIntegerField(default=0)),
                ('distinct_exercise_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm_version', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconception_states', to='curriculum.concept')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconception_states', to='learners.enrollment')),
            ],
            options={
                'ordering': ['enrollment_id', 'concept_id', '-confidence_score', 'code'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='misconc_state_status'), models.Index(fields=['enrollment', 'code'], name='misconc_state_code')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'concept', 'code'), name='misconceptions_state_unique_code'), models.CheckConstraint(condition=models.Q(('status__in', ['watch', 'active', 'resolved'])), name='misconceptions_state_status'), models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='misconceptions_state_confidence_range')],
            },
        ),
    ]
