# Generated by Django 5.2.17 on 2026-09-17 08:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('mastery_band', models.CharField(choices=[('not_started', 'Not started'), ('weak', 'Weak'), ('learning', 'Learning'), ('practising', 'Practising'), ('mastered', 'Mastered')], default='not_started', max_length=16)),
                ('retention_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('independence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('fluency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('trend', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('falling', 'Falling'), ('insufficient_data', 'Insufficient data')], default='insufficient_data', max_length=24)),
                ('trend_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-1')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('stability_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('retention_evidence_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm_version', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_states', to='curriculum.concept')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_states', to='learners.enrollment')),
            ],
            options={
                'ordering': ['enrollment_id', 'concept__skill__order', 'concept__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptModeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_mode', models.CharField(choices=[('recognise', 'Recognise'), ('complete', 'Complete'), ('fix', 'Fix'), ('create', 'Create')], max_length=16)),
                ('performance_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('independence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('fluency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_states', to='learner_intelligence.conceptstate')),
            ],
            options={
                'ordering': ['concept_state_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conceptstate',
            index=models.Index(fields=['enrollment', 'review_due_at'], name='learner_int_enrollm_999ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptstate',
            index=models.Index(fields=['enrollment', 'mastery_band'], name='learner_int_enrollm_c34d80_idx'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.UniqueConstraint(fields=('enrollment', 'concept'), name='learner_intel_state_unique_concept'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(('mastery_score__gte', 0), ('mastery_score__lte', 100)), name='learner_intel_state_mastery_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('retention_score__gte', 0), ('retention_score__lte', 100)), ('retention_score__isnull', True), _connector='OR'), name='learner_intel_state_retention_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('independence_score__gte', 0), ('independence_score__lte', 100)), ('independence_score__isnull', True), _connector='OR'), name='learner_intel_state_independence_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fluency_score__gte', 0), ('fluency_score__lte', 100)), ('fluency_score__isnull', True), _connector='OR'), name='learner_intel_state_fluency_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(('trend_score__isnull', True), models.Q(('trend_score__gte', -1), ('trend_score__lte', 1)), _connector='OR'), name='learner_intel_state_trend_score_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(('mastery_band__in', ['not_started', 'weak', 'learning', 'practising', 'mastered'])), name='learner_intel_state_band_valid'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(('trend__in', ['rising', 'stable', 'falling', 'insufficient_data'])), name='learner_intel_state_trend_valid'),
        ),
        migrations.AddConstraint(
            model_name='conceptstate',
            constraint=models.CheckConstraint(condition=models.Q(('stability_days__isnull', True), ('stability_days__lte', 60), _connector='OR'), name='learner_intel_state_stability_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptmodestate',
            constraint=models.UniqueConstraint(fields=('concept_state', 'learning_mode'), name='learner_intel_mode_unique'),
        ),
        migrations.AddConstraint(
            model_name='conceptmodestate',
            constraint=models.CheckConstraint(condition=models.Q(('learning_mode__in', ['recognise', 'complete', 'fix', 'create'])), name='learner_intel_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='conceptmodestate',
            constraint=models.CheckConstraint(condition=models.Q(('performance_score__gte', 0), ('performance_score__lte', 100)), name='learner_intel_mode_performance_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptmodestate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('independence_score__gte', 0), ('independence_score__lte', 100)), ('independence_score__isnull', True), _connector='OR'), name='learner_intel_mode_independence_range'),
        ),
        migrations.AddConstraint(
            model_name='conceptmodestate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fluency_score__gte', 0), ('fluency_score__lte', 100)), ('fluency_score__isnull', True), _connector='OR'), name='learner_intel_mode_fluency_range'),
        ),
    ]
